### ISSUE TITLE
Simplify Support Hours Widget/Visibility

### ISSUE THREAD

**Issue by jimtrue** [pods-framework/pods-support#6]
Write a quick function that determine the Day of Week and displays the current Support Hours with a link to Support Policy and Hours.

We could use same function to tailor the display/details on the Chat Window and Landing Page

**Comment by GaryJones** [comment]
I think this could be _too clever_.

If the current day's support hours have passed, then you might consider showing tomorrow's instead, but that assumes that the visitors is available tomorrow. 

By hiding the other info, you're making it less useful because you don't know the full context of the visitor.

Instead of hiding the rest, consider making it bold, or changing the colour (accessibility considerations) or underlining (usability considerations):

![screenshot 2018-06-04 21 01 04](https://user-images.githubusercontent.com/88371/40938728-8b82da76-683a-11e8-999a-9438bfd4c645.png)

**Comment by GaryJones** [comment]
For a bit of extra markup / JSON-LD, having the full list means that http://schema.org/OpeningHoursSpecification could be added, which _may_ be picked up and used by search engines on SERP snippets.

**Comment by jimtrue** [comment]
@GaryJones Thanks for this, completely missed it last year! ;) I went with just always showing the hours. We flag Opening & Closing in Slack, so it's not necessary to go crazy with this.

I'm actually closing this one, because we have it published in multiple places.
